apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u1w0j8759-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u1w0j8759-nodejs 
  name: u1w0j8759-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: u1w0j8759-nodejs 
